version: '3.8'
services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    image: amazoncorretto:11
    ports:
      - "8080:8080"
    depends_on:
      server:
         condition: service_started
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: amazoncorretto:11
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:13.7-alpine
    container_name: "database"
    ports:
      - "6541:5432"
    environment:
        - POSTGRES_DB=shareit
        - POSTGRES_USER=VanDarkholme
        - POSTGRES_PASSWORD=300bucks
